add test

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -28,9 +28,14 @@ jobs:
       - name: Wait for containers to start
         run: sleep 10
 
-      - name: Run tests
+      - name: Run API test
         run: |
-          # Run your tests here
+          response_code=$(curl -o /dev/null -s -w "%{http_code}" http://localhost:8080/clone-me)
 
-      - name: Stop and remove containers
-        run: docker-compose down
+          if [ "$response_code" -eq 200 ]; then
+            echo "API test passed. Received a 200 response."
+          else
+            echo "API test failed. Received a non-200 response: $response_code"
+            exit 1
+          fi
+
